name: Set up Node/npm/yarn
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: https://npm.pkg.github.com
          scope: '@neymansashka'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
         npm install
         npm publish
      #- run: echo 
      #- run: npm publish
        #env:
          #NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
