name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write
  
env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Publish and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: pnpm
          registry-url: 'https://npm.pkg.github.com'

      - name: Set config
        run: pnpm config set '//npm.pkg.github.com/:_authToken' "${NODE_AUTH_TOKEN}"
        shell: bash
        
      - name: Install deps
        run: pnpm install --frozen-lockfile
    
      - name: Publish
        run: pnpm run publishing
        
