name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]
        
jobs:
  release:
    name: Publish and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: pnpm
          registry-url: 'https://npm.pkg.github.com'
        
      - name: Install deps
        run: pnpm install --frozen-lockfile
    
      - name: Publish
        run: pnpm run publishing
        
